---
title: "Ford School Courses"
subtitle: ""
format:
    html: 
      toc: true
      code-fold: true
editor_options: 
  chunk_output_type: console
---


```{r global.options, include=FALSE}
knitr::opts_chunk$set(echo = T, # code is folded 
                      cache = F, # CACHE 
                      fig.width = 4.5, 
                      fig.height = 3.5,
                      split = T,
                      fig.align = 'center', 
                      fig.path='figs/',
                      fig.retina = 6,
                      warning = F, 
                      message = F)
```

```{r, echo=FALSE}
library(tidyverse)
library(rvest)
library(magrittr)
```


```{r results='asis'}
term = "fall/2025"

cat("#", term)
# load saved web data from code/courses.R
here::here("data", "courses.rda") |> load()

# filter to courses for the selected term
selected_courses <- filter(courses, str_detect(url, term) )

# for all selected_courses courses, go to the page  
for(i in 1:nrow(selected_courses)){
url <-  paste0("https://fordschool.umich.edu", selected_courses$url[i])
html <- read_html(url) # The course homepage
links <- html_nodes(html, "a") # "a" nodes are linked text


# the text of the course page 
description <- html |> 
  html_text2() |>
  as.character() |>
  # clean it up
  stringr::str_remove_all("(\n|.)*PubPol|\nTerm\n(\n|.)*\nCredit Hours|\nTo see additional course meeting information, please\n\nlogin with your U-M Level 1 password\n\nLevel|\nShare:\n(\n|.)*|Faculty Expert") 

paste0("#", description, "\n <", url, "> \n") |> 
  cat(sep = "\n", labels = url) 
 }

```
